---
monitoring_admin_password: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  64343366383132313132363936383261663731316435346335646439663032313534353033316362
  6434356432613632366339303834643731326262313561350a653538333465313732633533313161
  32396163383039303236646432623264626533356634303737326533656333303430343365613265
  3236363939663563340a613164336136343634386231313039316233393562396239656139646236
  37386164666231373466653135346334646463373565386533636366623837666136

# password set for user root
mariadb_root_password: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  64343366383132313132363936383261663731316435346335646439663032313534353033316362
  6434356432613632366339303834643731326262313561350a653538333465313732633533313161
  32396163383039303236646432623264626533356634303737326533656333303430343365613265
  3236363939663563340a613164336136343634386231313039316233393562396239656139646236
  37386164666231373466653135346334646463373565386533636366623837666136

# password set for backup user
mariadb_backup_password: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  64343366383132313132363936383261663731316435346335646439663032313534353033316362
  6434356432613632366339303834643731326262313561350a653538333465313732633533313161
  32396163383039303236646432623264626533356634303737326533656333303430343365613265
  3236363939663563340a613164336136343634386231313039316233393562396239656139646236
  37386164666231373466653135346334646463373565386533636366623837666136

# password set for replication user
mariadb_replication_password: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  64343366383132313132363936383261663731316435346335646439663032313534353033316362
  6434356432613632366339303834643731326262313561350a653538333465313732633533313161
  32396163383039303236646432623264626533356634303737326533656333303430343365613265
  3236363939663563340a613164336136343634386231313039316233393562396239656139646236
  37386164666231373466653135346334646463373565386533636366623837666136

# password set for default database user
mariadb_password: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  64343366383132313132363936383261663731316435346335646439663032313534353033316362
  6434356432613632366339303834643731326262313561350a653538333465313732633533313161
  32396163383039303236646432623264626533356634303737326533656333303430343365613265
  3236363939663563340a613164336136343634386231313039316233393562396239656139646236
  37386164666231373466653135346334646463373565386533636366623837666136
