---

gh_runner_config_url: https://github.com/legitYosal/gelara-lab
gh_runner_config_token: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  33396666666336613663373064653664653630656264643866376465616461336431363534303138
  3739653362623338663366653366313432336339623932640a393038343235363831623266646237
  33306530653238333736353164373062616266393563313137343836396666363733663761306530
  3062663866633966380a313237633433656366313862366565313639653662336339313632366164
  63363039383234623331313837393033383363663139633136353762326635663836
